//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.App.Resources
{
    
    internal partial class Extension
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Extension.manager == null))
                {
                    Extension.manager = new System.Resources.ResourceManager("Mp.App.Resources.Extension", typeof(Extension).Assembly);
                }
                return Extension.manager;
            }
        }
        internal static byte[] GetBytes(Extension.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            Extension = -3227,
        }
    }
}
