//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.App.Resources
{
    
    internal partial class Images
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Images.manager == null))
                {
                    Images.manager = new System.Resources.ResourceManager("Mp.App.Resources.Images", typeof(Images).Assembly);
                }
                return Images.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(Images.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            fsBack = -32286,
            btBack = -22201,
            imgWeather = -18865,
            fsFolder = -18406,
            imgRadio = -17658,
            btStop = -16368,
            imgAdd = -15635,
            bootLogo = -14380,
            imgSettings = -10671,
            btPlay = -4097,
            imgEdit = 1918,
            fsNone = 6427,
            fsMusic = 8941,
            btPause = 17392,
            imgMusic = 21393,
            btForward = 27662,
            imgDelete = 32340,
            imgRefresh = 32342,
        }
    }
}
