//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.App.Resources
{
    
    internal partial class LocalFonts
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((LocalFonts.manager == null))
                {
                    LocalFonts.manager = new System.Resources.ResourceManager("Mp.App.Resources.LocalFonts", typeof(LocalFonts).Assembly);
                }
                return LocalFonts.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(LocalFonts.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            clockfont_72 = 11238,
        }
    }
}
