//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.App.Resources
{
    
    internal partial class Plugins
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Plugins.manager == null))
                {
                    Plugins.manager = new System.Resources.ResourceManager("Mp.App.Resources.Plugins", typeof(Plugins).Assembly);
                }
                return Plugins.manager;
            }
        }
        internal static byte[] GetBytes(Plugins.BinaryResources id)
        {
            return ((byte[])(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            Flac_v140 = -1558,
        }
    }
}
