//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Ui.Resources
{
    
    internal partial class Fonts
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Fonts.manager == null))
                {
                    Fonts.manager = new System.Resources.ResourceManager("Mp.Ui.Resources.Fonts", typeof(Fonts).Assembly);
                }
                return Fonts.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(Fonts.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Arial_12_italic = -19493,
            Arial_18_italic = -11415,
            Arial_12_bold = -10097,
            Arial_9_regular = -7287,
            Arial_12_regular = -3754,
            Arial_18_regular = 3434,
            Arial_18_bold = 21923,
            Arial_9_bold = 22380,
            Arial_9_italic = 25814,
        }
    }
}
