//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mp.Ui.Resources
{
    
    internal partial class Images
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Images.manager == null))
                {
                    Images.manager = new System.Resources.ResourceManager("Mp.Ui.Resources.Images", typeof(Images).Assembly);
                }
                return Images.manager;
            }
        }
        internal static Microsoft.SPOT.Bitmap GetBitmap(Images.BitmapResources id)
        {
            return ((Microsoft.SPOT.Bitmap)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BitmapResources : short
        {
            clear = -31384,
            arrowRight = -28146,
            cmb_arrow = -25620,
            msg_delete = -23571,
            arrowLeft = -22030,
            backspace = -20879,
            msg_save = -19315,
            msg_info = -1223,
            enter = 1569,
            msg_search = 6639,
            msg_error = 20094,
            arrowUpDown = 27861,
            msg_question = 29124,
        }
    }
}
